config/routes.rb
Rails.application.routes.draw do
  root "statique#accueil"
  get "/contact", to: "statique#contact"
  get "/team", to: "statique#team"
  get "/services", to: "statique#services"
  get "/signup", to: "utilisateurs#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :utilisateurs
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :utilisateur
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :nom, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def Utilisateur.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def Utilisateur.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = Utilisateur.new_token
    update_attribute(:remember_digest, Utilisateur.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UtilisateurMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = Utilisateur.new_token
    update_attribute(:reset_digest, Utilisateur.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UtilisateurMailer.password_reset(self).deliver_now
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = Utilisateur.new_token
    self.activation_digest = Utilisateur.digest(activation_token)
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    utilisateur = Utilisateur.find_by(email: params[:email])
    if utilisateur && !utilisateur.activated? && utilisateur.authenticated?(:activation, params[:id])
      utilisateur.activate
      log_in utilisateur
      flash[:success] = "Compte activé!"
      redirect_to utilisateur
    else
      flash[:danger] = "Lien d'activation invalide"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @utilisateur = Utilisateur.find_by(email: params[:password_reset][:email].downcase)
    if @utilisateur
      @utilisateur.create_reset_digest
      @utilisateur.send_password_reset_email
      flash[:info] = "Un e-mail a été envoyé avec les instructions pour récupérer votre mot de passe."
      redirect_to root_url
    else
      flash.now[:danger] = "Adresse e-mail non trouvée"
      render "new"
    end
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    utilisateur = Utilisateur.find_by(email: params[:session][:email].downcase)
    if utilisateur && utilisateur.authenticate(params[:session][:password])
      if utilisateur.activated?
        log_in utilisateur
        params[:session][:remember_me] == "1" ? remember(utilisateur) : forget(utilisateur)
        redirect_to utilisateur
      else
        message = "Le compte n'est pas activé. "
        message += "Vérifier votre e-mail pour le lien d'activation."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = "E-mail ou mot de passe invalide !"
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/statique_controller.rb
class StatiqueController < ApplicationController
  def accueil
  end

  def contact
  end

  def team
  end

  def services
  end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  before_action :logged_in_utilisateur, only: [:index, :edit, :update, :destroy]
  before_action :correct_utilisateur, only: [:edit, :update, :destroy]
  before_action :admin_utilisateur, only: :destroy

  def index
    @utilisateurs = Utilisateur.paginate(page: params[:page])
  end

  def show
    @utilisateur = Utilisateur.find(params[:id])
  end

  def new
    @utilisateur = Utilisateur.new
  end

  def create
    @utilisateur = Utilisateur.new(utilisateur_params)
    if @utilisateur.save
      @utilisateur.send_activation_email
      flash[:info] = "Merci de consulter votre e-mail pour le lien d'activation de votre compte."
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @utilisateur = Utilisateur.find(params[:id])
  end

  def update
    @utilisateur = Utilisateur.find(params[:id])
    if @utilisateur.update_attributes(utilisateur_params)
      flash[:success] = "Profile mis à jour"
      redirect_to @utilisateur
    else
      render "edit"
    end
  end

  def destroy
    Utilisateur.find(params[:id]).destroy
    flash[:success] = "Utilisateur supprimé"
    redirect_to utilisateurs_url
  end

  private

  def utilisateur_params
    params.require(:utilisateur).permit(:nom, :email, :password,
                                        :password_confirmation)
  end

  def logged_in_utilisateur
    unless logged_in?
      flash[:danger] = "Merci de vous connecter."
      redirect_to login_url
    end
  end

  def correct_utilisateur
    @utilisateur = Utilisateur.find(params[:id])
    redirect_to(root_url) unless current_utilisateur?(@utilisateur)
  end

  def admin_utilisateur
    redirect_to(root_url) unless current_utilisateur.admin?
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(utilisateur)
    session[:utilisateur_id] = utilisateur.id
  end

  def current_utilisateur
    if (utilisateur_id = session[:utilisateur_id])
      @current_utilisateur ||= Utilisateur.find_by(id: utilisateur_id)
    elsif (utilisateur_id = cookies.signed[:utilisateur_id])
      utilisateur = Utilisateur.find_by(id: utilisateur_id)
      if utilisateur && utilisateur.authenticated?(:remember, cookies[:remember_token])
        log_in utilisateur
        @current_utilisateur = utilisateur
      end
    end
  end

  def remember(utilisateur)
    utilisateur.remember
    cookies.permanent.signed[:utilisateur_id] = utilisateur.id
    cookies.permanent[:remember_token] = utilisateur.remember_token
  end

  def current_utilisateur?(utilisateur)
    utilisateur == current_utilisateur
  end

  def logged_in?
    !current_utilisateur.nil?
  end

  def forget(utilisateur)
    utilisateur.forget
    cookies.delete(:utilisateur_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_utilisateur)
    session.delete(:utilisateur_id)
    @current_utilisateur = nil
  end
end

app/helpers/statique_helper.rb
module StatiqueHelper
  def full_title(page_title = "")
    base_title = "Tutoriel RoR Udemy"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
  def gravatar_for(utilisateur, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(utilisateur.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: utilisateur.nom, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer>
    <p>&copy; 2018. Tous droits réservés.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to image_tag("logo-kairios.jpg", alt: "Logo gCKn"), root_path, class: "logo" %>
        <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Accueil", root_path %></li>
            <li><%= link_to "Services", services_path %></li>
            <li><%= link_to "Team", team_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <% if logged_in? %>
                <li><%= link_to "Utilisateurs", utilisateurs_path %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Compte <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profil", current_utilisateur %></li>
                        <li><%= link_to "Paramètres", edit_utilisateur_path(current_utilisateur) %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Déconnexion", logout_path, method: :delete %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Se connecter", login_path %></li>
            <% end %>
        </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <section class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/new.html.erb
<% provide(:title, "Mot de passe oublié") %>

<h1 class="register-title">Mot de passe oublié</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Envoyer", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @utilisateur.errors.any? %>
  <div class="alert alert-danger">
    Le formulaire contient <%= pluralize(@utilisateur.errors.count, "erreur") %>.
  </div>
  <ul class="list-form">
  <% @utilisateur.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/statique/accueil.html.erb
<% provide(:title, "Accueil") %>

<div class="center jumbotron">
    <h1>Bienvenue !</h1>

    <p>&darr; Pour vous inscrire, cliquez simplement sur le bouton ci-dessous &darr;</p>

    <%= link_to "S'inscrire maintenant", signup_url, class: "btn btn-lg btn-primary" %>
</div>

app/views/statique/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Statique#contact</h1>
<p>Find me in app/views/statique/contact.html.erb</p>

app/views/statique/services.html.erb
<% provide(:title, "Services") %>

<h1>Statique#services</h1>
<p>Find me in app/views/statique/services.html.erb</p>

app/views/statique/team.html.erb
<% provide(:title, "Team") %>

<h1>Statique#team</h1>
<p>Find me in app/views/statique/team.html.erb</p>

app/views/utilisateurs/_utilisateur.html.erb
<li>
  <%= gravatar_for utilisateur, size: 50 %>
  <%= link_to utilisateur.nom, utilisateur %>
  <% if current_utilisateur.admin? && !current_utilisateur?(utilisateur) %>
  | <%= link_to "supprimer", utilisateur, method: :delete,
                                data: { confirm: "Supprimer l'utilisateur ?" } %>
  <% end %>
</li>

app/views/utilisateurs/edit.html.erb
<% provide(:title, "Editer mon profil") %>

<h1 class="register-title">Mettre à jour votre profil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@utilisateur) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :nom %>
      <%= f.text_field :nom, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @utilisateur %>
      <a href="http://gravatar.com/emails" target="_blank">changer l'image</a>
    </div>
  </div>
</div>

app/views/utilisateurs/index.html.erb
<% provide(:title, 'Tous les utilisateurs') %>
<h1>Tous les utilisateurs</h1>

<%= will_paginate %>

<ul class="utilisateurs">
  <% @utilisateurs.each do |utilisateur| %>
    <%= render utilisateur %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/utilisateurs/new.html.erb
<% provide(:title, "S'enregistrer") %>

<h1 class="register-title">S'enregistrer</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@utilisateur) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :nom %>
      <%= f.text_field :nom, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/utilisateurs/show.html.erb
<% provide(:title, @utilisateur.nom) %>

<div class="row">
  <aside class="col-md-4">
    <section class="info_utilisateur">
      <h1>
        <%= gravatar_for @utilisateur %>
        <%= @utilisateur.nom %>
      </h1>
    </section>
  </aside>
</div>